using System.Collections.Generic;

namespace Manicomio.SwosPlayerFinder.Core
{
    public class Countries
    {
        private static readonly Dictionary<byte, string> _playerCountries;

        private static readonly Dictionary<byte, string> _teamCountries;

        static Countries()
        {
            _playerCountries = new Dictionary<byte, string>
                {
                    {0, "ALBANIA"},
                    {1, "AUSTRIA"},
                    {2, "BELGIUM"},
                    {3, "BULGARIA"},
                    {4, "CROATIA"},
                    {5, "CYPRUS"},
                    {6, "CZECH REP"},
                    {7, "DENMARK"},
                    {8, "ENGLAND"},
                    {9, "ESTONIA"},
                    {10, "FAEROE ISL"},
                    {11, "FINLAND"},
                    {12, "FRANCE"},
                    {13, "GERMANY"},
                    {14, "GREECE"},
                    {15, "HUNGARY"},
                    {16, "ICELAND"},
                    {17, "ISRAEL"},
                    {18, "ITALY"},
                    {19, "LATVIA"},
                    {20, "LITHUANIA"},
                    {21, "LUXEMBOURG"},
                    {22, "MALTA"},
                    {23, "HOLLAND"},
                    {24, "NORTHERN IRELAND"},
                    {25, "NORWAY"},
                    {26, "POLAND"},
                    {27, "PORTUGAL"},
                    {28, "ROMANIA"},
                    {29, "RUSSIA"},
                    {30, "SAN MARINO"},
                    {31, "SCOTLAND"},
                    {32, "SLOVENIA"},
                    {33, "SWEDEN"},
                    {34, "TURKEY"},
                    {35, "UKRAINE"},
                    {36, "WALES"},
                    {37, "SERBIA MONTENEGRO"},
                    {38, "BELARUS"},
                    {39, "SLOVAKIA"},
                    {40, "SPAIN"},
                    {41, "ARMENIA"},
                    {42, "BOSNIA HERC"},
                    {43, "AZERBAIJAN"},
                    {44, "GEORGIA"},
                    {45, "SWITZERLAND"},
                    {46, "REP IRELAND"},
                    {47, "FYR MACEDONIA"},
                    {48, "TURKMENISTAN"},
                    {49, "LIECHTENSTEIN"},
                    {50, "MOLDOVA"},
                    {51, "COSTA RICA"},
                    {52, "EL SALVADOR"},
                    {53, "GUATEMALA"},
                    {54, "HONDURAS"},
                    {55, "BAHAMAS"},
                    {56, "MEXICO"},
                    {57, "PANAMA"},
                    {58, "USA"},
                    {59, "BAHRAIN"},
                    {60, "NICARAGUA"},
                    {61, "BERMUDA"},
                    {62, "JAMAICA"},
                    {63, "TRINIDAD TOBAGO"},
                    {64, "CANADA"},
                    {65, "BARBADOS"},
                    {66, "EL SALVADOR"},
                    {67, "ST VINCENT GREN"},
                    {68, "ARGENTINA"},
                    {69, "BOLIVIA"},
                    {70, "BRAZIL"},
                    {71, "CHILE"},
                    {72, "COLOMBIA"},
                    {73, "ECUADOR"},
                    {74, "PARAGUAY"},
                    {75, "SURINAM"},
                    {76, "URUGUAY"},
                    {77, "VENEZUELA"},
                    {78, "GUYANA"},
                    {79, "PERU"},
                    {80, "ALGERIA"},
                    {81, "SOUTH AFRICA"},
                    {82, "BOTSWANA"},
                    {83, "BURKINA FASO"},
                    {84, "BURUNDI"},
                    {85, "LESOTHO"},
                    {86, "CONGO ZAIRE"},
                    {87, "ZAMBIA"},
                    {88, "GHANA"},
                    {89, "SENEGAL"},
                    {90, "IVORY COAST"},
                    {91, "TUNISIA"},
                    {92, "MALI"},
                    {93, "MADAGASCAR"},
                    {94, "CAMEROON"},
                    {95, "CHAD"},
                    {96, "UGANDA"},
                    {97, "LIBERIA"},
                    {98, "MOZAMBIQUE"},
                    {99, "KENYA"},
                    {100, "SUDAN"},
                    {101, "SWAZILAND"},
                    {102, "ANGOLA"},
                    {103, "TOGO"},
                    {104, "ZIMBABWE"},
                    {105, "EGYPT"},
                    {106, "TANZANIA"},
                    {107, "NIGERIA"},
                    {108, "ETHIOPIA"},
                    {109, "GABON"},
                    {110, "SIERRA LEONE"},
                    {111, "BENIN"},
                    {112, "CONGO"},
                    {113, "GUINEA"},
                    {114, "SRI LANKA"},
                    {115, "MOROCCO"},
                    {116, "GAMBIA"},
                    {117, "MALAWI"},
                    {118, "JAPAN"},
                    {119, "TAIWAN"},
                    {120, "INDIA"},
                    {121, "BANGLADESH"},
                    {122, "BRUNEI"},
                    {123, "IRAQ"},
                    {124, "JORDAN"},
                    {125, "SRI LANKA"},
                    {126, "SYRIA"},
                    {127, "SOUTH KOREA"},
                    {128, "IRAN"},
                    {129, "VIETNAM"},
                    {130, "MALAYSIA"},
                    {131, "SAUDI ARABIA"},
                    {132, "YEMEN"},
                    {133, "KUWAIT"},
                    {134, "LAOS"},
                    {135, "NORTH KOREA"},
                    {136, "OMAN"},
                    {137, "PAKISTAN"},
                    {138, "PHILIPPINES"},
                    {139, "CHINA"},
                    {140, "SINGAPORE"},
                    {141, "MAURITIUS"},
                    {142, "MYANMAR"},
                    {143, "PAPUA NEW GUINEA"},
                    {144, "THAILAND"},
                    {145, "UZBEKISTAN"},
                    {146, "QATAR"},
                    {147, "UTD ARAB EMIRATES"},
                    {148, "AUSTRALIA"},
                    {149, "NEW ZEALAND"},
                    {150, "FIJI"},
                    {151, "SOLOMON ISL"},
                    {152, "CUSTOM"}
                };
            
            _teamCountries = new Dictionary<byte, string>
                {
                    {0, "ALBANIA"},
                    {1, "AUSTRIA"},
                    {2, "BELGIUM"},
                    {3, "BULGARIA"},
                    {4, "CROATIA"},
                    {5, "CYPRUS"},
                    {6, "CZECH REP"},
                    {7, "DENMARK"},
                    {8, "ENGLAND"},
                    {10, "ESTONIA"},
                    {11, "FAEROE ISL"},
                    {12, "FINLAND"},
                    {13, "FRANCE"},
                    {14, "GERMANY"},
                    {15, "GREECE"},
                    {16, "HUNGARY"},
                    {17, "ICELAND"},
                    {18, "REP IRELAND"},
                    {19, "ISRAEL"},
                    {20, "ITALY"},
                    {21, "LATVIA"},
                    {22, "LITHUANIA"},
                    {23, "LUXEMBOURG"},
                    {24, "MALTA"},
                    {25, "HOLLAND"},
                    {26, "NORTHERN IRELAND"},
                    {27, "NORWAY"},
                    {28, "POLAND"},
                    {29, "PORTUGAL"},
                    {30, "ROMANIA"},
                    {31, "RUSSIA"},
                    {32, "SAN MARINO"},
                    {33, "SCOTLAND"},
                    {34, "SLOVENIA"},
                    {35, "SPAIN"},
                    {36, "SWEDEN"},
                    {37, "SWITZERLAND"},
                    {38, "TURKEY"},
                    {39, "UKRAINE"},
                    {40, "WALES"},
                    {41, "SERBIA MONTENEGRO"},
                    {42, "ALGERIA"},
                    {43, "ARGENTINA"},
                    {44, "AUSTRALIA"},
                    {45, "BOLIVIA"},
                    {46, "BRAZIL"},
                    {47, "COSTA RICA"},
                    {48, "CHILE"},
                    {49, "COLOMBIA"},
                    {50, "ECUADOR"},
                    {51, "EL SALVADOR"},
                    {55, "JAPAN"},
                    {60, "MEXICO"},
                    {62, "NEW ZEALAND"},
                    {64, "PARAGUAY"},
                    {65, "PERU"},
                    {66, "SURINAM"},
                    {67, "TAIWAN"},
                    {69, "SOUTH AFRICA"},
                    {71, "URUGUAY"},
                    {73, "USA"},
                    {75, "INDIA"},
                    {76, "BELARUS"},
                    {77, "VENEZUELA"},
                    {78, "SLOVAKIA"},
                    {79, "GHANA"},
                    {83, "EL SALVADOR"}
                };

            // 68, "SOUTH AFRICA"
            // 69, "URUGUAY"
        }

        public static string GetPlayerCountry(byte id)
        {
            return _playerCountries[id];
        }

        public static string GetTeamCountry(byte id)
        {
            return _teamCountries[id];
        }
    }
}